name: flutter_native_badge_platform_interface
description: A common platform interface for the flutter_native_badge plugin.
repository: https://github.com/isaacadariku/flutter_native_badge/tree/main/flutter_native_badge_foundation
issue_tracker: https://github.com/isaacadariku/flutter_native_badge/issues
version: 1.0.4

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

scripts: derry.yaml
