name: flutter_native_badge_platform_interface
description: A common platform interface for the flutter_native_badge plugin.
repository: https://github.com/isaacadariku/flutter_native_badge/tree/main/flutter_native_badge_foundation
issue_tracker: https://github.com/isaacadariku/flutter_native_badge/issues
version: 1.0.1

environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
