name: flutter_native_badge
description: Flutter plugin for setting the badge count on native platforms.
  Wraps the native APIs for iOS and macOS to set the badge count on the app icon.
repository: https://github.com/isaacadariku/flutter_native_badge
issue_tracker: https://github.com/isaacadariku/flutter_native_badge/issues
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_native_badge_foundation:
    path: ../flutter_native_badge_foundation
  flutter_native_badge_platform_interface:
    path: ../flutter_native_badge_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        default_package: flutter_native_badge_foundation
      macos:
        default_package: flutter_native_badge_foundation
